### ISSUE TITLE
Special workflow for Maestro E2E when using Expo

### ISSUE THREAD

**Issue by maciekstosio** [software-mansion/setup-ci#112]
This one seems to work well on dev client with different scenarios. For non expo project we can leave as it is 

```
appId: com.maciekstosio.myexpoapp
---
- launchApp
- runFlow:
    when:
        visible: 'Development Build'
    commands:
        - tapOn:
            text: http://.*:8081
- runFlow:
    when:
        visible: 'Continue'
    commands:
        - tapOn:
            point: 25%, 25%
- assertVisible:
    text: 'Home'
```
